### ISSUE TITLE
List amount "-1" shows nothing

### ISSUE THREAD

**Issue by allesweb** [Advanced-Post-List/advanced-post-list#122]
Hi!

I have a couple of lists working fine with defined list amounts >= 0. But when choosing -1 (or moving the slider to its leftmost position), the list is empty.

Is this a bug or am I doing something wrong?

// Andreas

**Comment by EkoJr** [comment]
It is a known issue with WordPress, and seems to be getting more defunct as time passes.

The only resolve available is to use a large number for the List Amount that you don't expect to reach.

**Comment by allesweb** [comment]
OK, thanks for your reply.

In that case it would be great if I could choose a higher amount than 100.

**Comment by EkoJr** [comment]
It can :)

Along the right side of the slider, there is another counter that works in conjunction. You can either click the up button, or you can select the text field and input the number. So, instead of 100, you can add an extra zero and make it 1000.

**Comment by allesweb** [comment]
:-) Well, I think that was too obvious, haha! Thanks!

**Comment by EkoJr** [comment]
No prob.
