### ISSUE TITLE
Error generating code for new preset

### ISSUE THREAD

**Issue by Trebly** [Advanced-Post-List/advanced-post-list#40]
Hi,
I just changes the post-status to create à list using : "simplePostList_5" added "simplePostList_All5".
I get an error (missing probaly some """ or ",") following screenshot
![image](https://cloud.githubusercontent.com/assets/1492375/5474723/cccda6a8-8613-11e4-84e9-95ee6f7691ad.png)

Trebly

https://wordpress.org/support/topic/lots-of-errors-12
https://wordpress.org/support/topic/error-generating-code-for-default-presets-of-03b8

**Comment by EkoJr** [comment]
Are you still getting this error? Because it is difficult to make out in the screenshot since it seems to be rendering in HTML instead of Text.

**Comment by Trebly** [comment]
Hi,
I don't use currently anymore Advanced Post list.
Nevertheless I remember well what was happening.
I tried to define new sets of parameters, I was getting an error displaying a panel of quite same content as the one which appears on the screenshot (data of the parameters definition - displaying the corresponding json text with a syntax error : the soft unable to read the json data as valid and reproducing the string red).
I thought that I had made errors in the parameters syntax...
Finally I just load default parameters sets and rename the any set to store them (keeping capability to make changes later) : I generate quite the same error.

Then I was sure that the soft was producing an error in encoding json file of parameters (or errors into the samples...), which was appearing at reading data as invalid.

Easy to reproduce : just load a (each) default parameters set and try to save it on another name : this was producing the error systematically. This need to check sets using separately the different elementary parameters because some could be saved (post_list5 was creating the error).

Then I stop to try to use the product.

Best regards

Trebly

**Comment by EkoJr** [comment]
What I found strange was that the Preset JSON string reads back as a 'success', and then it also reads multiple Before, Content, and After...but i do suppose i JSON syntax error could be the culprit. 

I just wish i could of seen the raw data at the time, but i had to put APL on the shelf for awhile because of other matters.

**Comment by EkoJr** [comment]
New Admin UI
