### ISSUE TITLE
Conflict with MagicMembers

### ISSUE THREAD

**Issue by MaciekRyd** [Advanced-Post-List/advanced-post-list#44]
Hi,
I decided to provide this info, as there is no new version, so perhaps it may help in taking into account this problem before it is released.

Please, see attached screenshots. While Advanced Post List is active, Magic Memebers control panel is destroyed... It looks like some formatting issue...

Here it is like it should look like (plugin turned off):
![advanced post list plugin not active](https://cloud.githubusercontent.com/assets/3254691/8332227/1b999c7a-1a8d-11e5-9a06-acac4e991998.jpg)

And here is how it looks:
![advanced post list plugin active](https://cloud.githubusercontent.com/assets/3254691/8332228/1b9fa746-1a8d-11e5-9917-e43c59e2541d.jpg)

![advanced post list plugin version](https://cloud.githubusercontent.com/assets/3254691/8332229/1ba1e0b0-1a8d-11e5-962d-84afee14a6a7.jpg)

Overall your plugin is GREAT and I cannot replace it, so your suport would be nicely welcome...

Regards,
Maciej
maciej.rydlewicz@softdesk.pl

**Comment by EkoJr** [comment]
This issue is likely to disappear with the new Admin Page for APL 0.4.
