### ISSUE TITLE
Use wordpress default UI style

### ISSUE THREAD

**Issue by jooola** [Advanced-Post-List/advanced-post-list#74]
Could we add a theme or something to use the default wordpress theme ?

When installing this plugins some other plugins get the same styles of this plugin : contact forms 7 for exemple : 
![image](https://cloud.githubusercontent.com/assets/19195485/25955275/12fc9956-3669-11e7-9aef-b22a9b5a9732.png)

And by default shoudl look like this : 

![image](https://cloud.githubusercontent.com/assets/19195485/25955308/274476d6-3669-11e7-8181-16b49097459e.png)

I think the admin UI needs a UI refactor and not be able to use different jquery themes i don't this is usefull !

**Comment by EkoJr** [comment]
One of the plans is to redo the Admin UI in 0.4. I just been having a hard time allocating time.

I want to change the design to WordPress's default styling, but I am also trying to preserve some the UX designs.

**Comment by EkoJr** [comment]
Related to #75 development.
