### ISSUE TITLE
Custom Post Type

### ISSUE THREAD

**Issue by baskettcase** [Advanced-Post-List/advanced-post-list#95]
I have one custom post type that shows up in your admin area, but select parent dropdown is disabled and nothing else is shown that I can select. What do I need to do to get that post type to be selectable?

**Comment by EkoJr** [comment]
Sounds like the CPT isn't set to hierarchical (pages), and doesn't have categories or tags associated to it.

The current v0.3.X has a concept flaw that doesn't allow you to select just the CPT itself that have nothing else associated with it. The beta version v0.4 implemented this fix to allow JUST the CPT to be selected...unfortunately, it's not ready for release.

For now, you could probably add a taxonomy, but with WP, there is no default category setting for CPTs.

**Comment by baskettcase** [comment]
Ok thanks, I appreciate the fast response. Since I needed it quickly, I just did a WPQuery and custom page, but I will keep this plugin in mind for the future. Thanks!

**Comment by EkoJr** [comment]
Wish I could provide a resolve, but I understand.

The concept has been implemented in the next version, and is open for beta testers, but I've been reserving a public release until everything is better polished.
