### ISSUE TITLE
Post_Tags issue

### ISSUE THREAD

**Issue by epikentros** [Advanced-Post-List/advanced-post-list#98]
Hi,

I found a problem trying to use the options for [Post_Tags] code.
Even if I write - links="false" - the plugin still put the link.
Following the corrected code from class-apl-shortcodes.php file.
Hope to do it right!
Thanks,
Enrico.
```
	public function post_tags( $atts ) {
		// INIT.
		$atts_value = shortcode_atts( array(
			'delimiter' => ', ',
			'links' => 'true',
		), $atts, 'post_tags');
		$return_str = '';

		// STEP 1.
/*		$atts_value['links'] = true; THIS IS THE PROBLEM - THEN I CHANGE IT */
		$links = true; /* STARTS FROM HERE NOW */
		if ( 'false' === strtolower( $atts_value['links'] ) ) {
			$links = false; /* HERE ANOTHER CHANGE */
		}

		// STEP 2.
		$post_tags = get_the_tags( $this->_post->ID );
		$array_total = count( $post_tags );
		$i = 1;
		if ( $post_tags ) {
			// STEP 3.
			foreach ( $post_tags as $tag ) {
				if ( $links ) { /* HERE ANOTHER CHANGE */
					$return_str .= '<a href="' . get_tag_link( $tag->term_id ) . '" >' . $tag->name . '</a>';
				} else {
					$return_str .= $tag->name;
				}

				if ( $array_total > $i ) {
					$return_str .= $atts_value['delimiter'];
				}
				$i++;
			}
		}
```

**Comment by EkoJr** [comment]
Thank you for reporting in this.

I'm surprised this got pushed like this. Looks like when the all Internal Shortcodes were being worked on, it was hiding in plain sight, but the whole internal shortcode functionality got a much needed restructure.

I plan on having an update out for 0.4 within a week on a Monday. Unless something pushes it back. I'll be adding this fix to that, and may loop around and add this to the 0.3 branch.

Until then, for anyone else trying to troubleshoot, the [Post_Terms](https://github.com/Advanced-Post-List/advanced-post-list/wiki/Internal-Shortcode-%7C-%5BPost_Terms%5D) provide the same results.

**Comment by epikentros** [comment]
glad to read such a quick response!
Thanks for your great work!
